apiVersion: v1
kind: Service
metadata:
  name: sampleapp
  labels:
    creator: adhoctestingenvironments
spec:
  selector:
    app: sampleapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP