apiVersion: apps/v1
kind: Deployment
metadata:
  name: adhoctestingenvironments
spec:
  selector:
    matchLabels:
      app: adhoctestingenvironments
  template:
    metadata:
      labels:
        app: adhoctestingenvironments
    spec:
      containers:
        - name: adhoctestingenvironments
          image: claudeglauser/adhoctestingenvironments:latest
          resources:
            requests:
              memory: "100Mi"
              cpu: "0.25"
            limits:
              memory: "1000Mi"
              cpu: "1"
          env: 
            - name: KubernetesAccessToken
              valueFrom:
                secretKeyRef:
                  name: adhoctestingenvironmentsecret
                  key: kubernetesaccesstoken
            - name: KubernetesHost
              valueFrom:
                secretKeyRef:
                  name: adhoctestingenvironmentsecret
                  key: kuberneteshost
            - name: ASPNETCORE_URLS
              value: "https://+;http://+"
            - name: ASPNETCORE_HTTPS_PORT
              value: "443"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              value: "bla"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: "/adteconfig/certificate.pfx"
          volumeMounts: 
            - name: config-volume
              mountPath: /adteconfig
      volumes:
        - name: config-volume
          configMap:
            name: theconfigmap

