apiVersion: v1
kind: Service
metadata:
  name: adhoctestingenvironments
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
    - port: 80
      name: http-port
      targetPort: 80
      protocol: TCP
    - port: 443
      name: https-port
      targetPort: 443
      protocol: TCP    
  type: LoadBalancer
  selector:
    app: adhoctestingenvironments