using AdHocTestingEnvironments.Model.Entities;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AdHocTestingEnvironments.Data
{
    public static class InMemoryDbInitializer
    {
        public static void InitAdHocTestingEnvironmentDb(this IApplicationBuilder app)
        {
            using (var serviceScope = app.ApplicationServices.GetService<IServiceScopeFactory>().CreateScope())
            {
                var context = serviceScope.ServiceProvider.GetRequiredService<AdHocTestingEnvironmentsContext>();
                context.Database.EnsureCreated();

                ApplicationInfoEntity app1 = new ApplicationInfoEntity()
                {
                    Name = "sampleapplication",
                    ContainerImage = "claudeglauser/sample-webapp:latest",
                    HasDatabase = true,
                    InitSql = "CREATE DATABASE test;\n\\connect test;\nCREATE TABLE IF NOT EXISTS \"__EFMigrationsHistory\" ( \"MigrationId\" character varying(150) NOT NULL, \"ProductVersion\" character varying(32) NOT NULL, CONSTRAINT \"PK___EFMigrationsHistory\" PRIMARY KEY (\"MigrationId\") );\n START TRANSACTION;\n CREATE TABLE \"GuestBookEntry\" ( \"Id\" integer GENERATED BY DEFAULT AS IDENTITY, \"Text\" text NULL, CONSTRAINT \"PK_GuestBookEntry\" PRIMARY KEY (\"Id\") );\n INSERT INTO \"__EFMigrationsHistory\" (\"MigrationId\", \"ProductVersion\") VALUES ('20210626104025_InitialCreate', '5.0.7');\n COMMIT;",
                };
                context.Add(app1);              

                ApplicationInfoEntity app2 = new ApplicationInfoEntity()
                {
                    Name = "angularsample",
                    ContainerImage = "claudeglauser/sampleangularapp:latest",
                    HasDatabase = false,
                };
                context.Add(app2);

                ApplicationInfoEntity app3 = new ApplicationInfoEntity()
                {
                    Name = "postsample",
                    ContainerImage = "docker.tools.post.ch/samplewebapp:0.0.1-main.2",
                    HasDatabase = false,
                    InitSql = "CREATE DATABASE test;\n\\connect test;\nCREATE TABLE IF NOT EXISTS \"__EFMigrationsHistory\" ( \"MigrationId\" character varying(150) NOT NULL, \"ProductVersion\" character varying(32) NOT NULL, CONSTRAINT \"PK___EFMigrationsHistory\" PRIMARY KEY (\"MigrationId\") );\n START TRANSACTION;\n CREATE TABLE \"GuestBookEntry\" ( \"Id\" integer GENERATED BY DEFAULT AS IDENTITY, \"Text\" text NULL, CONSTRAINT \"PK_GuestBookEntry\" PRIMARY KEY (\"Id\") );\n INSERT INTO \"__EFMigrationsHistory\" (\"MigrationId\", \"ProductVersion\") VALUES ('20210626104025_InitialCreate', '5.0.7');\n COMMIT;",
                };
                context.Add(app3);

                context.SaveChanges();

            }
        }
    }
}
